package(default_visibility = ["//visibility:public"])
load("@build_bazel_rules_apple//apple/internal:apple_universal_binary.bzl", "apple_universal_binary")
load("@rules_xcodeproj//xcodeproj:defs.bzl", "top_level_target", "xcodeproj")

apple_universal_binary(
    name = "circe_bin",
    binary = "//Circe:_binary",
    minimum_os_version = "12",
    platform_type = "macos",
)

xcodeproj(
    name = "xcodeproj",
    project_name = "Circe",
    tags = ["manual"],
    top_level_targets = [
        top_level_target(":circe_bin", target_environments = ["device"]),
    ],
    bazel_path = "../bazel-wrapper",
)
