package(default_visibility = ["//visibility:public"])
load("@rules_xcodeproj//xcodeproj:defs.bzl", "top_level_target", "xcodeproj")

xcodeproj(
    name = "xcodeproj",
    project_name = "Circe",
    tags = ["manual"],
    top_level_targets = [
        top_level_target("//Circe:Circe", target_environments = ["device"]),
    ],
    bazel_path = "../bazel-wrapper",
)
